### List All cars
GET http://localhost:3000/api/listCars

### Save new car
POST http://localhost:3000/api/createCar
Content-Type: application/json

{
	"title" : "Civic",
	"brand" : "Honda",
	"price" : "36.000.00",
	"age": 2009
}

### List logs
GET http://localhost:3000/api/logs
